[package]
name = "DanLu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.25"
crossterm = "0.26.1"
lipsum = "0.9.0"
rand = "0.8.5"
ratatui = "0.21.0"
strum_macros = "0.24.3"
